---
title: "ky_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Exploratory analysis of Kentucy pretrial and court data 
```{r cars}
library(tidyverse)
library(magrittr)
library(docstring)
library(DataExplorer)

data_path = "../KY Pretrial + Court Data FY 10-18/"

```


```{r}
defendents_df = read.table(paste0(data_path,"01_KY_Recidivism_Defendants.txt"), header = T, sep = "|", fill = T, strip.white = T)

interviews_df = read.table(paste0(data_path,"02_KY_Recidivism_Interviews.txt"), header = T, sep = "|", fill = T, strip.white = T)

cnet_cases_df = read.table(paste0(data_path,"03_KY_Recidivism_CNet_Cases.txt"), header = T, sep = "|", fill = T, strip.white = T)

prim_cases_df = read.table(paste0(data_path,"04_KY_Recidivism_PRIM_Cases.txt"), header = T, sep = "|", fill = T, strip.white = T)

case_crossref_df = read.table(paste0(data_path,"05_KY_Recidivism_Case_Cross_Reference.txt"), header = T, sep = "|", fill = T, strip.white = T)

cnet_charges_df = read.table(paste0(data_path,"06_KY_Recidivism_CNet_Charges.txt"), header = T, sep = "|", fill = T, strip.white = T)

prim_charges_df = read.table(paste0(data_path,"07_KY_Recidivism_PRIM_Charges.txt"), header = T, sep = "|", fill = T, strip.white = T)

sentences_df = read.table(paste0(data_path,"08_KY_Recidivism_Sentences.txt"), header = T, sep = "|", fill = T, strip.white = T)

bonds_df = read.table(paste0(data_path,"09_KY_Recidivism_Bonds.txt"), header = T, sep = "|", fill = T, strip.white = T)

events_df = read.table(paste0(data_path,"10_KY_Recidivism_Events.txt"), header = T, sep = "|", fill = T, strip.white = T)

fta_df = read.table(paste0(data_path,"11_KY_Recidivism_FTA.txt"), header = T, sep = "|", fill = T, strip.white = T)

supervision_df = read.table(paste0(data_path,"12_KY_Recidivism_Supervision.txt"), header = T, sep = "|", fill = T, strip.white = T)

```


```{r}
summarize_data <- function(data_list,data_path){
  #'Data summary function
  #'
  #'data_list: a list of names of the datasets (strings)
  #'data_path: string of the root directory of the data
  
  for (dataname in data_list){
    print(dataname)
    df = read.table(paste0(data_path,dataname), header = T, sep = "|", fill = T, strip.white = T)
    summary(df)
    plot_str(df)
    plot_missing(df)
    # plot_histogram(df)
    plot_bar(df)
    # plot_correlation(df)
    rm(df)
  }
}
```




```{r}
data_list = c("01_KY_Recidivism_Defendants.txt", "02_KY_Recidivism_Interviews.txt" ,"03_KY_Recidivism_CNet_Cases.txt","04_KY_Recidivism_PRIM_Cases.txt","05_KY_Recidivism_Case_Cross_Reference.txt", "06_KY_Recidivism_CNet_Charges.txt", "07_KY_Recidivism_PRIM_Charges.txt", "08_KY_Recidivism_Sentences.txt", "09_KY_Recidivism_Bonds.txt", "10_KY_Recidivism_Events.txt", "11_KY_Recidivism_FTA.txt","12_KY_Recidivism_Supervision.txt")
# data_list= c("01_KY_Recidivism_Defendants.txt")
data_path = "../KY Pretrial + Court Data FY 10-18/"

summarize_data(data_list, data_path)
```

