---
title: "Broward Outcomes Analysis"
output: html_notebook
---


```{r}
library(tidyverse)
library(magrittr)
library(reshape2)
```

```{r}
data_path = ""
load(paste0(data_path,"compas_psa.Rdata"))
scores_outcomes = compas_psa_wide %>%
                  filter(`Risk of Violence_decile_score`>=0, `Risk of Recidivism_decile_score`>=0, 
                         `Risk of Failure to Appear_decile_score`>=0)%>%
                  left_join(outcomes, by=c("person_id","screening_date"))

```

```{r}
ggplot(scores_outcomes, aes(x=`Risk of Violence_decile_score`, y=recid_violent)) +
     geom_jitter(shape=1, colour="steelblue", fill = "steelblue", alpha = .5)  +
     ggtitle("Violent Recidivism Score vs True Outcome") +
     xlab("COMPAS Violence Decile Score") +
     ylab("Recidivation Indicator") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))

ggplot(scores_outcomes, aes(x=`arnold_nvca_raw`, y=recid_violent)) +
     geom_jitter(shape=1, colour="steelblue", fill = "steelblue", alpha = .5)  +
     ggtitle("True Outcome vs Arnold NVCA Raw") +
     xlab("Arnold NVCA Raw") +
     ylab("Recidivation Indicator") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))

ggplot(scores_outcomes, aes(x=`arnold_nvca_raw`, y=`Risk of Violence_decile_score`)) +
     # geom_point()+
     geom_jitter(shape=1, colour="steelblue", fill = "steelblue", alpha = .5)  +
     # ggtitle("True Outcome vs Arnold NVCA Raw") +
     xlab("Arnold NVCA Raw") +
     ylab("COMPAS") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))


```


Calculating the 10-quantiles for all 3 Arnold PSA scores and all 3 COMPAS scores. 
Note that for the Arnold NVCA, we use the raw score so as to obtain a quantile; the NVCA is the only one out of the Arnold Scores which has a binary yes/no flag. 
```{r}
scores_quantiles = data.frame( 
  quant_id=seq.int(1,5),
  arnold_nvca_raw = quantile(scores_outcomes$arnold_nvca_raw, probs = seq(0,1,.25),na.rm = T, names = F),
  arnold_nca = quantile(scores_outcomes$arnold_nca, probs = seq(0,1,.25),na.rm = T, names = F),
  arnold_fta = quantile(scores_outcomes$arnold_fta, probs = seq(0,1,.25),na.rm = T, names = F),
  compas_viol = quantile(scores_outcomes$`Risk of Violence_decile_score`,
                       probs = seq(0,1,.25),na.rm = T, names = F),
  compas_recid = quantile(scores_outcomes$`Risk of Recidivism_decile_score`,
                       probs = seq(0,1,.25),na.rm = T, names = F),
  compas_fta = quantile(scores_outcomes$`Risk of Failure to Appear_decile_score`,
                       probs = seq(0,1,.25),na.rm = T, names = F)
  )

ggplot(melt(scores_quantiles, id.vars = c("quant_id", "arnold_nvca_raw", "arnold_nca", "arnold_fta")), 
  aes(x=arnold_nvca_raw, y=value,color = variable)) +
     geom_point()+ geom_line() +
     ggtitle("Arnold NVCA Raw vs Compas  Quantiles") +
     xlab("Arnold Quartiles") +
     ylab("COMPAS Quartiles") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))

ggplot(melt(scores_quantiles, id.vars = c("quant_id", "arnold_nvca_raw", "arnold_nca", "arnold_fta")), 
  aes(x=arnold_nca, y=value,color = variable)) +
     geom_point()+ geom_line() +
     ggtitle("Arnold NCA vs Compas Quantiles") +
     xlab("Arnold Quartiles") +
     ylab("COMPAS Quartiles") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))

ggplot(melt(scores_quantiles, id.vars = c("quant_id", "arnold_nvca_raw", "arnold_nca", "arnold_fta")), 
  aes(x=arnold_fta, y=value,color = variable)) +
     geom_point()+ geom_line() +
     ggtitle("Arnold FTA vs Compas Quartiles") +
     xlab("Arnold FTA Quartiles") +
     ylab("COMPAS Quartiles") +
     theme(text=element_text(size=18),
           axis.ticks=element_line(size=1),
           axis.ticks.length = unit(3, "mm"))

```

