---
title: "baselines_recid_broward"
author: "Beau Coker"
date: "11/5/2018"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(warning=F, message=F,echo = TRUE)
knitr::opts_knit$set(root.dir = '/tmp')
```


```{r include = FALSE}
library(tidyverse)
library(magrittr)
library(ROCR)
library(caret)
library(ggplot2)
require(caret)
```


```{r}
data_path = "C:/Users/binha/Documents/Duke/Cynthia Research/KY-analysis-mytrials/broward/data/"
load(paste0(data_path, "compas_psa.Rdata"))
load(paste0(data_path, "expanded_features.Rdata"))
labels = read_csv("~/Duke/Cynthia Research/KY-analysis-mytrials/broward/data/labels.csv") %>% 
    mutate(screening_date = as.Date(screening_date, format = "%m/%d/%Y"))
```

```{r}
### Add useful columns to features and apply row filters used for all models
features_filt = features_before_on %>%
  select(-p_incarceration) %>% 
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  mutate(sex = ifelse(sex == "Male", 1, 0)) %>% #change sex variable to numeric encoding
  inner_join(features_on, by = c("person_id","screening_date")) %>%
    inner_join(
        psa_features%>%
            select(-c(p_current_age, p_prison)), 
        by = c("person_id","screening_date")) %>%
    inner_join(outcomes, by = c("person_id","screening_date")) %>%
    inner_join(
        features %>% 
            select(person_id, screening_date, p_incarceration, years_since_last_crime, six_month, 
                   one_year, three_year, five_year), 
        by = c("person_id", "screening_date")) %>% 
    filter(`Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1) %>% # Filter 1
    filter(!is.na(current_offense_date)) %>% # Filter 3
  filter(screening_date <= current_offense_date_limit) %>% # Filter 4
  mutate(decile_use = `Risk of Recidivism_decile_score`) # Select recidivism or violent recidivism decile score to use in this script

## Select features
df = features_filt %>%
  transmute(
    person_id,
    sex,
    race,
    screening_date,
    
    #COMPAS Risk of Recidivism Features\
    p_current_age,
    p_age_first_offense,
    p_charge,
    #p_jail30 = p_jail30,
    #p_prison = p_prison,
    p_incarceration = p_incarceration,
    p_probation = p_probation,
    
    #COMPAS Risk of violent recidivism features
    p_juv_fel_count,
    p_felprop_violarrest,
    p_murder_arrest,
    p_felassault_arrest,
    p_misdemassault_arrest,
    p_famviol_arrest,
    p_sex_arrest,
    p_weapons_arrest,
    
    #PSA Features (which were not named above)
    fail_appear_two_yr, 
    fail_appear_two_plus,
    current_violent, 
    current_violent20, 
    pending_charge, 
    prior_conviction_F, 
    prior_conviction_M, 
    violent_conviction, 
    total_convictions, 
    
    #Misc Features
    p_arrest,
    p_property,
    p_traffic,
    p_drug,
    p_dui,
    p_domestic,
    p_stalking,
    p_voyeurism,
    p_fraud,
    p_stealing,
    p_trespass,
    years_since_last_crime,
    six_month,
    one_year,
    three_year,
    five_year) %>%
  na.omit()
```


```{r}
## compass & arnold
scores_outcomes = compas_psa_wide %>%
  filter(`Risk of Violence_decile_score`>=0, 
         `Risk of Recidivism_decile_score`>=0, 
         `Risk of Failure to Appear_decile_score`>=0)%>%
  left_join(outcomes, by=c("person_id","screening_date")) %>%
  merge(x=., y=df %>% select(person_id, screening_date, sex, race), 
        by = c("person_id", "screening_date"))
```


## combine data sets

```{r}
colnames(labels)
```


```{r}
## merge df with labels
df = merge(x=df, y =labels, by=c('person_id', 'screening_date'))%>% 
    select(person_id:general_six_month, 
           drug_two_year, 
           property_two_year,
           misdemeanor_two_year,
           felony_two_year,
           violent_two_year,           
           drug_six_month, 
           property_six_month,
           misdemeanor_six_month,
           felony_six_month,
           violent_six_month)%>% 
    mutate(general_two_year = as.factor(general_two_year),
           drug_two_year = as.factor(drug_two_year),
           property_two_year = as.factor(property_two_year),
           felony_two_year = as.factor(felony_two_year),
           misdemeanor_two_year = as.factor(misdemeanor_two_year),
           violent_two_year = as.factor(violent_two_year),
           general_six_month = as.factor(general_six_month),
           drug_six_month = as.factor(drug_six_month),
           property_six_month = as.factor(property_six_month),
           felony_six_month = as.factor(felony_six_month),
           misdemeanor_six_month = as.factor(misdemeanor_six_month),
           violent_six_month = as.factor(violent_six_month))
```


```{r}
### split train and test for those models with 5-general-CV
set.seed(816)
test_sample = sample(1:nrow(df), 0.2*nrow(df), replace = FALSE)
test = df[test_sample,]
train = df[-test_sample, ]
test_index = 1:nrow(df)
test_index = ifelse(test_index %in% test_sample, 1, 0)
```

## save data
```{r}
write.csv(df, file = "broward_data.csv", row.names = F)
write.csv(train, file = "broward_train.csv", row.names = F)
write.csv(test, file = "broward_test.csv", row.names = F)
write.csv(scores_outcomes, file = "broward_arnold.csv", row.names = F)
#write.csv(test_index, file = "broward_test_index.csv", row.names = F, col.names = F)
#write.csv(fold, file = "fold_index.csv", row.names = F, col.names = F)
```






## Appendix
```{r}
## 5-CV index
flds <- createFolds(train$recid_two_year, 
                    k = 5, 
                    list = TRUE, 
                    returnTrain = FALSE)
fold = 1:nrow(df)
fold[fold %in% flds$Fold1] = "a"
fold[fold %in% flds$Fold2] = "b"
fold[fold %in% flds$Fold3] = "c"
fold[fold %in% flds$Fold4] = "d"
fold[fold %in% flds$Fold5] = "e"

fold[fold == "a"] = 1
fold[fold == "b"] = 2
fold[fold == "c"] = 3
fold[fold == "d"] = 4
fold[fold == "e"] = 5
fold=as.numeric(fold)

#train = sample_frac(df,.8)
#test = anti_join(df, train, by = 'person_id')
```













