---
title: "data_adaboost"
author: "Caroline Wang"
date: "April 18, 2019"
output: html_document
purpose: "bin data values for adaboost, riskslim approaches "
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=F, message=F,echo = TRUE)
library(tidyverse)
```

```{r}
data_path = "../data/"
load(paste0(data_path,"expanded_features.Rdata"))
load(paste0(data_path,"compas_psa.Rdata"))

```

```{r}
### Add useful columns to features and apply row filters used for all models
features_filt = features_before_on %>%
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  mutate(sex = ifelse(sex == "Male", 0, 1)) %>% #change sex variable to numeric encoding
  inner_join(features_on, by = c("person_id","screening_date")) %>%

  inner_join(
    psa_features%>%
      select(-c(p_current_age,p_prison)), 
    by = c("person_id","screening_date"))%>%
  inner_join(outcomes, by = c("person_id","screening_date")) %>%
  filter(`Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1) %>% # Filter 1
  filter(!is.na(current_offense_date)) %>% # Filter 3
  filter(screening_date <= current_offense_date_limit) %>% # Filter 4
  mutate(recid_use = recid) # Select recidivism or violent recidivism to use in this script 

         
## Select features and round count features
df = features_filt %>%
  na.omit()%>%
  #variables to remove entirely from data
  select(-c(`Risk of Recidivism_decile_score`, `Risk of Recidivism_raw_score`,
           `Risk of Violence_decile_score`, `Risk of Violence_raw_score`,
           `Risk of Failure to Appear_decile_score`, `Risk of Failure to Appear_raw_score`,
           race,name, recid, recid_violent,
           first_offense_date, current_offense_date, screening_date
           )
         )%>%
  #mutate only at variables in vars
  mutate_at(vars(p_current_age, p_age_first_offense), 
            funs(eighteen = if_else(. <=18, 1, 0), 
                 nineteen = if_else(. <=19, 1, 0),
                 twenty = if_else(. <=20, 1, 0),
                 twenty1 = if_else(. <=21, 1, 0),
                 twenty2 = if_else(. <=22, 1, 0),
                 twenty3 = if_else(. <=23, 1, 0),
                 twenty4 = if_else(. <=24, 1, 0),
                 twenty6 = if_else(. <=26, 1, 0),
                 twenty8 = if_else(. <=28, 1, 0),
                 thirty = if_else(. <=30, 1, 0),
                 thirty2 = if_else(. <=32, 1, 0),
                 thirty4 = if_else(. <=34, 1, 0),
                 thirty6 = if_else(. <=36, 1, 0),
                 thirty8 = if_else(. <=38, 1, 0),
                 forty = if_else(. <=40, 1, 0),
                 forty4 = if_else(. <=44, 1, 0),
                 forty8 = if_else(. <=48, 1, 0),
                 fifty2 = if_else(. <=52, 1, 0),
                 fifty6 = if_else(. <=56, 1, 0),
                 sixty = if_else(. <=60, 1, 0),
                 sixty5 = if_else(. <=65, 1, 0)
            ))

#get the names of the age var just created
name_features_filt = names(features_filt)
names_df = names(df)
age_names_new = setdiff(names_df, name_features_filt)

#get the names of the original variables which were not converted to stumps
static_feat_names = c("person_id", "recid_use") #features which are not converted to stumps
names2rm = setdiff(setdiff(names_df, static_feat_names), age_names_new)

df <- df %>%  
  #mutate at everything except the variables in vars 
  mutate_at(vars(-person_id, -recid_use, -age_names_new, -p_age_first_offense, -p_current_age),
            funs(one = if_else(. >=1, 1, 0), 
                 two = if_else(. >=2, 1, 0), 
                 three = if_else(.>=3, 1, 0),
                 four = if_else(.>=4, 1, 0),
                 five = if_else(.>=5, 1, 0),
                 six = if_else(.>=6, 1, 0),
                 seven = if_else(.>=7, 1, 0),
                 eight = if_else(.>=8, 1, 0),
                 nine = if_else(.>=9, 1, 0)
           )) %>%
  select(-names2rm)  #remove original, unmutated variables (except for those in the vars func above )
  
#label must be first column for riskSLIM
set.seed(283)
train = df %>% sample_frac(.8)
test = df %>% anti_join(train, by = 'person_id') #change to account for screening date!

train = select(train, -person_id)
test = select(test, -person_id)

train=train[,c(ncol(train),2:ncol(train)-1)]
test=test[,c(ncol(test),2:ncol(test)-1)]

```


Reorder columns so that recid_use is first. This is required for riskSLIM. 
```{r}
train = train[,c(2,1,3:ncol(train))]
test = test[,c(2,1,3:ncol(test))]

names(test)
# df[,c(1,3,2,4,5:50)]
```


```{r}
write.table(train, file=paste0(data_path, "train_stumps.csv"),
            sep=",", row.names = F)
write.table(test, file=paste0(data_path, "test_stumps.csv"),
            sep=",", row.names = F)

```

